# Python Packages

1. NumPy
2. Pandas
3. Matplotlib
4. Seaborn
5. Sklearn
6. Requests
7. NLTK

# NumPy

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3]
type(list1)

list

In [3]:
arr = np.array(list1)

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

1

In [7]:
np.array([arr]).ndim

2

### Built in methods

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.arange(10,15,2)

array([10, 12, 14])

In [11]:
np.arange(5,15, dtype = float)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

### Zeros and Ones

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros(3, dtype = int)

array([0, 0, 0])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones(3, dtype = int)

array([1, 1, 1])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Linspace

In [18]:
np.linspace(0,10,5) ## 0-10 is divided into 5 parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,50,6)

array([ 0., 10., 20., 30., 40., 50.])

### Eye

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(2, dtype = int)

array([[1, 0],
       [0, 1]])

In [22]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

### Random

1. np.random.rand()
2. np.random.randn()
3. np.random.randint()

##### 1. np.random.rand()

In [24]:
np.random.rand(3)

array([0.61798947, 0.6066593 , 0.6231058 ])

In [25]:
np.random.rand(3)

array([0.25296221, 0.00351417, 0.19350208])

In [26]:
np.random.rand(3)

array([0.2266197 , 0.41616005, 0.12760029])

In [29]:
np.random.rand(3,3)

array([[0.30124221, 0.64769282, 0.05076028],
       [0.98355993, 0.54494537, 0.33109179],
       [0.64976815, 0.65198528, 0.53272284]])

##### 2. np.random.randn()

In [30]:
np.random.randn(3)

array([-0.1266379 , -0.11921053, -0.08730658])

In [31]:
np.random.randn(3)

array([-0.09611174, -0.18934009,  0.88761644])

In [32]:
np.random.randn(3)

array([ 0.79517251,  1.26662523, -1.01421506])

In [33]:
np.random.randn(3,4)

array([[ 0.97680132,  0.26383036,  0.26655002,  0.65585241],
       [-0.42250201,  0.80287042, -1.51303858,  0.32922033],
       [-0.17533904,  0.57859069,  0.39670347,  1.3224045 ]])

In [34]:
np.random.randn(3,4) + 4

array([[3.71735783, 5.36435214, 4.37382185, 5.89421314],
       [3.99397897, 4.56880672, 1.8041309 , 3.85773867],
       [4.67057879, 3.95458229, 3.70868273, 5.12763311]])

##### 3. np.random.randint()

In [36]:
np.random.randint(4)

1

In [37]:
np.random.randint(4)

0

In [38]:
np.random.randint(4)

2

In [39]:
np.random.randint(30,54)

53

In [40]:
np.random.randint(30,54)

52

### Array Attributes and methods 

1. Reshape
2. Shape
3. Dtype

##### 1. Reshape

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr = np.arange(8)

In [48]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [50]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
arr.reshape(1,8)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

##### 2. Shape

In [54]:
arr.shape

(8,)

In [55]:
arr.reshape(4,2).shape

(4, 2)

##### 3. Dtype

In [56]:
arr.dtype

dtype('int32')

### Indexing and Selection

In [57]:
arr = np.arange(1,11)

In [58]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[2]

3

In [60]:
arr[-1]

10

In [61]:
arr[:5]

array([1, 2, 3, 4, 5])

In [62]:
arr[3:6]

array([4, 5, 6])

In [63]:
arr[2:8:3]

array([3, 6])

In [64]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Broadcasting

In [65]:
x = np.array([5,3,2,4])
y = np.array([6,9,12,41])

In [66]:
z = x + y
z

array([11, 12, 14, 45])

In [67]:
x = np.array([5,3,2,4,7])

In [68]:
x + 7

array([12, 10,  9, 11, 14])

In [70]:
x = np.array([[5,3,2,4], [1,7,3,6]])

In [71]:
x + 7

array([[12, 10,  9, 11],
       [ 8, 14, 10, 13]])

### Indexing of 2D Array/Matrix

In [72]:
arr_2d = np.array([[5,18,3], [3,6,2], [4,9,2]])
arr_2d

array([[ 5, 18,  3],
       [ 3,  6,  2],
       [ 4,  9,  2]])

In [74]:
arr_2d.shape

(3, 3)

In [75]:
arr_2d.ndim

2

In [76]:
arr_2d[1][1]

6

In [77]:
arr_2d[2][0]

4

In [78]:
arr_2d[:,1]

array([18,  6,  9])

In [79]:
arr_2d[:,:1]

array([[5],
       [3],
       [4]])

In [80]:
arr_2d[:,-1]

array([3, 2, 2])

In [81]:
arr_3d = np.array([[[5,18,3], [3,6,2], [4,9,2]]])
arr_3d

array([[[ 5, 18,  3],
        [ 3,  6,  2],
        [ 4,  9,  2]]])

In [82]:
arr_3d.ndim

3

In [83]:
arr_3d.shape

(1, 3, 3)

### Fancy Indexing

In [84]:
arr = np.zeros([3,3])

In [85]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [86]:
arr.shape

(3, 3)

In [88]:
arr_len = arr.shape[0]

In [89]:
for i in range(arr_len):
    arr[i] = i
    print(arr[i])

[0. 0. 0.]
[1. 1. 1.]
[2. 2. 2.]


In [90]:
arr[[2,1]]

array([[2., 2., 2.],
       [1., 1., 1.]])

### Selection

In [91]:
arr = np.arange(0,10)

In [92]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [94]:
arr[arr > 5]

array([6, 7, 8, 9])

### NumPy Operations

In [95]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [99]:
arr / arr

C:\Users\sanja\AppData\Local\Temp/ipykernel_17236/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [100]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### Universal Array Functions

In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
np.min(arr)

0

In [104]:
np.max(arr)

9

In [105]:
np.log(arr)

C:\Users\sanja\AppData\Local\Temp/ipykernel_17236/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Append, Concat and Stack

##### 1. Append

In [106]:
arr = np.array([[1,2,3],[2,3,4],[3,4,5]])

In [107]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [108]:
arr.shape

(3, 3)

In [109]:
arr.ndim

2

In [110]:
arr1 = np.array([[4,5,6]])

In [111]:
arr1

array([[4, 5, 6]])

In [112]:
arr1.shape

(1, 3)

In [113]:
arr1.ndim

2

In [114]:
arr2 = np.array([[1],[2],[3]])

In [115]:
arr2

array([[1],
       [2],
       [3]])

In [116]:
arr2.shape

(3, 1)

In [117]:
arr2.ndim

2

In [118]:
np.append(arr, arr1, axis = 0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [120]:
np.append(arr, arr2, axis = 1)

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])

##### 2. Concatenate

In [121]:
np.concatenate((arr,arr1), axis = 0)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [123]:
np.concatenate((arr,arr2), axis = 1)

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])

##### 3. Stack

In [124]:
np.vstack((arr, arr1))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [125]:
np.hstack((arr,arr2))

array([[1, 2, 3, 1],
       [2, 3, 4, 2],
       [3, 4, 5, 3]])